#!/usr/bin/env python3
"""
train_multi_mlp.py
-------------------
Trains 5 MLP sizes (16,8) -> (256,128,32) on the DoH/DGA feature CSVs from
Gio's original notebook, and exports each model TWICE:

  1) as a C header (scalar/NEON/AVX kernels include this directly), reusing
     the same array layout as the original notebook's export_mlp_to_c()
  2) as ONNX (via skl2onnx) so onnxruntime can run the identical model

All 5 sizes share the SAME 16 input features -> hidden sizes are always
multiples of 8 (16, 8, 32, 64, 128, 256) so the vectorized kernels never
need a tail loop on hidden layers. The output layer (1 or C classes) is
small and is always handled with a plain scalar loop in the C kernels,
regardless of platform -- vectorizing a 1-8 wide output buys nothing.

Usage:
    # with your real datasets (same paths as the notebook):
    python3 train_multi_mlp.py --data-root /home/ubuntu/DoH_DGA_training --N 16

    # to smoke-test the whole pipeline without real data:
    python3 train_multi_mlp.py --synthetic --n-samples 20000
"""
import argparse
import json
import os
import sys

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

TOP_FEATURES = [
    "client_pkt_max", "n_client", "bytes_fraction_client", "n_server",
    "pkt_fraction_client", "client_bytes", "server_pkt_max", "size_min",
    "size_mean", "server_pkt_mean", "dir_switches", "server_bytes",
    "size_max", "client_pkt_min", "server_pkt_min", "client_pkt_mean",
]  # 16 features -- matches notebook order exactly (order matters for C/ONNX parity)

# 5 sizes, easiest-to-train (smallest) first. All hidden layer widths are
# multiples of 8 by construction.
MODEL_SIZES = [
    (16, 8),
    (32, 16),
    (64, 32),
    (128, 64, 16),
    (256, 128, 32),
]


def load_real_data(data_root, N_value):
    paths = {
        "doh_tunnel_iodine": f"{data_root}/datasets/PCAPs/DoHMalicious/iodine/all_pcaps_allN.csv",
        "doh_tunnel_dns2tcp": f"{data_root}/datasets/PCAPs/DoHMalicious/dns2tcp/all_pcaps_allN.csv",
        "doh_tunnel_dnscat2": f"{data_root}/datasets/PCAPs/DoHMalicious/dnscat2/all_pcaps_allN.csv",
        "dga_google": f"{data_root}/datasets/DGA_Google/all_pcaps_allN.csv",
        "dga_cloudflare": f"{data_root}/datasets/DGA_CF/all_pcaps_allN.csv",
        "dga_adguard": f"{data_root}/datasets/DGA_ADGuard/all_pcaps_allN.csv",
        "dga_quad9": f"{data_root}/datasets/DGA_Quad9/all_pcaps_allN.csv",
        "dga_hkd": f"{data_root}/datasets/DGA_HKD/all_pcaps_allN.csv",
        "nondoh_benign": f"{data_root}/datasets/PCAPs/DoHBenign-NonDoH/all_nondoh.csv",
        "doh_benign": f"{data_root}/datasets/PCAPs/DoHBenign-NonDoH/all_doh.csv",
    }
    frames = []
    for name, p in paths.items():
        if os.path.exists(p):
            frames.append(pd.read_csv(p))
        else:
            print(f"[WARN] missing {name}: {p}", file=sys.stderr)
    if not frames:
        raise FileNotFoundError(
            "No dataset CSVs found under --data-root. Use --synthetic to smoke-test instead."
        )
    df_all = pd.concat(frames, ignore_index=True)
    df_subset = df_all[df_all["N"] == N_value].copy() if "N" in df_all.columns else df_all
    return df_subset


def make_synthetic_data(n_samples, n_classes=2, seed=42):
    """Class-separable synthetic data with the same 16 feature names, purely
    for pipeline validation (train/export/inference-parity), NOT for real
    accuracy numbers."""
    rng = np.random.default_rng(seed)
    centers = rng.normal(0, 3, size=(n_classes, len(TOP_FEATURES)))
    y = rng.integers(0, n_classes, size=n_samples)
    X = centers[y] + rng.normal(0, 1.0, size=(n_samples, len(TOP_FEATURES)))
    df = pd.DataFrame(X, columns=TOP_FEATURES)
    labels = [f"class_{c}" for c in range(n_classes)]
    df["label"] = [labels[c] for c in y]
    return df


def write_array_to_c(name, array, f, add_f_suffix=True):
    shape = array.shape
    flat = array.flatten()
    f.write(f"// Shape: {shape}\n")
    f.write(f"static const float {name}[{len(flat)}] ALIGN32 = {{\n    ")
    if add_f_suffix:
        f.write(", ".join(f"{float(x):.8f}f" for x in flat))
    else:
        f.write(", ".join(f"{float(x):.8f}" for x in flat))
    f.write("\n};\n\n")


def export_mlp_to_c(model, out_path, tag):
    with open(out_path, "w") as f:
        f.write(f"// Auto-generated MLP weights for '{tag}' -- DO NOT EDIT BY HAND\n")
        f.write("// Generated by train_multi_mlp.py from scikit-learn MLPClassifier\n\n")
        f.write("#pragma once\n\n")
        f.write("#define ALIGN32 __attribute__((aligned(32)))\n\n")

        n_layers = len(model.coefs_)
        f.write(f"#define NUM_LAYERS {n_layers}\n\n")

        output_size = model.coefs_[-1].shape[1]
        num_classes = 2 if output_size == 1 else output_size
        f.write(f"#define NUM_CLASSES {num_classes}\n\n")

        in_size = model.coefs_[0].shape[0]
        sizes = [in_size] + [w.shape[1] for w in model.coefs_]
        f.write("static const int LAYER_SIZES[NUM_LAYERS+1] = { " +
                ", ".join(str(int(s)) for s in sizes) + " };\n\n")

        f.write(f"#define OUTPUT_SIZE {output_size}\n\n")
        f.write("#if OUTPUT_SIZE == 1\n")
        f.write("    #define IS_BINARY_CLASSIFICATION 1\n")
        f.write("    #define IS_MULTICLASS_CLASSIFICATION 0\n")
        f.write("#else\n")
        f.write("    #define IS_BINARY_CLASSIFICATION 0\n")
        f.write("    #define IS_MULTICLASS_CLASSIFICATION 1\n")
        f.write("#endif\n\n")

        for idx, (W, b) in enumerate(zip(model.coefs_, model.intercepts_)):
            W = W.astype(np.float32, copy=False)
            B = b.astype(np.float32, copy=False)
            write_array_to_c(f"W{idx}", W, f)
            write_array_to_c(f"B{idx}", B, f)

        f.write("// Weight & bias pointers per layer\n")
        f.write("static const float *WEIGHTS[NUM_LAYERS] = { " +
                 ", ".join(f"W{j}" for j in range(n_layers)) + " };\n")
        f.write("static const float *BIASES[NUM_LAYERS]  = { " +
                 ", ".join(f"B{j}" for j in range(n_layers)) + " };\n\n")
        f.write("#undef ALIGN32\n")


def export_feature_stats(scaler, feature_cols, out_path):
    means = scaler.mean_.astype(np.float32)
    stds = scaler.scale_.astype(np.float32)
    stds[stds == 0.0] = 1.0
    with open(out_path, "w") as f:
        f.write("// Auto-generated feature stats for z-score normalization\n\n")
        f.write("#pragma once\n\n")
        f.write("#define ALIGN32 __attribute__((aligned(32)))\n\n")
        f.write(f"#define NUM_FEATURES {len(means)}\n\n")
        f.write("static const float FEATURE_MEAN[NUM_FEATURES] ALIGN32 = {\n    ")
        f.write(", ".join(f"{float(m):.8f}f" for m in means))
        f.write("\n};\n\n")
        f.write("static const float FEATURE_STD[NUM_FEATURES] ALIGN32 = {\n    ")
        f.write(", ".join(f"{float(s):.8f}f" for s in stds))
        f.write("\n};\n\n")
        f.write("#undef ALIGN32\n")


def export_onnx(model, scaler, feature_cols, out_path):
    """Export the *identical* trained model to ONNX, folding the
    StandardScaler into the graph so the ONNX and C paths take the same
    raw (unscaled) 16-feature input -- fair apples-to-apples benchmark."""
    from skl2onnx import to_onnx
    from skl2onnx.common.data_types import FloatTensorType
    from sklearn.pipeline import Pipeline

    pipe = Pipeline([("scaler", scaler), ("mlp", model)])
    onx = to_onnx(
        pipe,
        initial_types=[("input", FloatTensorType([None, len(feature_cols)]))],
        target_opset=17,
    )
    with open(out_path, "wb") as f:
        f.write(onx.SerializeToString())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-root", default="/home/ubuntu/DoH_DGA_training")
    ap.add_argument("--N", type=int, default=16, help="N value column filter (packet window)")
    ap.add_argument("--synthetic", action="store_true", help="use synthetic data instead of real CSVs")
    ap.add_argument("--n-samples", type=int, default=20000)
    ap.add_argument("--out", default="../models")
    args = ap.parse_args()

    out_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), args.out))
    os.makedirs(out_dir, exist_ok=True)

    if args.synthetic:
        print("[INFO] Using SYNTHETIC data -- pipeline validation only, not real accuracy.")
        df = make_synthetic_data(args.n_samples)
    else:
        df = load_real_data(args.data_root, args.N)

    y = df["label"]
    X = df[TOP_FEATURES].copy()

    le = LabelEncoder()
    y_enc = le.fit_transform(y)
    n_classes = len(le.classes_)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.3, random_state=42,
        stratify=y_enc if n_classes > 1 else None,
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    manifest = {"features": TOP_FEATURES, "n_classes": int(n_classes), "models": []}

    for sizes in MODEL_SIZES:
        tag = "_".join(str(s) for s in sizes)
        print(f"\n=== Training MLP{sizes} ===")
        mlp = MLPClassifier(
            hidden_layer_sizes=sizes,
            activation="relu",
            solver="adam",
            alpha=1e-4,
            batch_size=64,
            learning_rate="adaptive",
            learning_rate_init=0.001,
            max_iter=300,
            shuffle=True,
            early_stopping=True,
            validation_fraction=0.1,
            n_iter_no_change=20,
            random_state=42,
            verbose=False,
        )
        mlp.fit(X_train_s, y_train)
        y_pred = mlp.predict(X_test_s)
        report = classification_report(y_test, y_pred, target_names=le.classes_, digits=4, zero_division=0)
        print(report)

        c_header = os.path.join(out_dir, f"model_{tag}.h")
        onnx_path = os.path.join(out_dir, f"model_{tag}.onnx")
        export_mlp_to_c(mlp, c_header, tag)
        export_onnx(mlp, scaler, TOP_FEATURES, onnx_path)

        layer_sizes = [mlp.coefs_[0].shape[0]] + [w.shape[1] for w in mlp.coefs_]
        print(f"[OK] {c_header}")
        print(f"[OK] {onnx_path}")
        print(f"     layer_sizes={layer_sizes}")

        manifest["models"].append({
            "tag": tag,
            "hidden_sizes": list(sizes),
            "layer_sizes": layer_sizes,
            "c_header": os.path.relpath(c_header, out_dir),
            "onnx": os.path.relpath(onnx_path, out_dir),
        })

    feat_header = os.path.join(out_dir, "feature_stats.h")
    export_feature_stats(scaler, TOP_FEATURES, feat_header)
    manifest["feature_stats_header"] = os.path.basename(feat_header)

    with open(os.path.join(out_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"\n[OK] wrote manifest.json with {len(manifest['models'])} models to {out_dir}")


if __name__ == "__main__":
    main()
